// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhmeTbmodeubANNw4Qg0hzc2ISb_VuKqU',
    appId: '1:672493454938:web:0236d017a1b918efadfa63',
    messagingSenderId: '672493454938',
    projectId: 'touchmeapp-d3af9',
    authDomain: 'touchmeapp-d3af9.firebaseapp.com',
    storageBucket: 'touchmeapp-d3af9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdUF91LymNFeqxAdLz7ee1gw9F_OcSH0c',
    appId: '1:672493454938:android:bd0a8ef81fb5b28cadfa63',
    messagingSenderId: '672493454938',
    projectId: 'touchmeapp-d3af9',
    storageBucket: 'touchmeapp-d3af9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBnsWN1Lhj7BNuQwIwY6nDFgvve3cCINg',
    appId: '1:672493454938:ios:2156c9c74d035b92adfa63',
    messagingSenderId: '672493454938',
    projectId: 'touchmeapp-d3af9',
    storageBucket: 'touchmeapp-d3af9.firebasestorage.app',
    iosBundleId: 'com.example.touchMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBnsWN1Lhj7BNuQwIwY6nDFgvve3cCINg',
    appId: '1:672493454938:ios:2156c9c74d035b92adfa63',
    messagingSenderId: '672493454938',
    projectId: 'touchmeapp-d3af9',
    storageBucket: 'touchmeapp-d3af9.firebasestorage.app',
    iosBundleId: 'com.example.touchMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhmeTbmodeubANNw4Qg0hzc2ISb_VuKqU',
    appId: '1:672493454938:web:9acf3c9d47ea809dadfa63',
    messagingSenderId: '672493454938',
    projectId: 'touchmeapp-d3af9',
    authDomain: 'touchmeapp-d3af9.firebaseapp.com',
    storageBucket: 'touchmeapp-d3af9.firebasestorage.app',
  );
}
