name: touch_me
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.1.2
  location: ^6.0.2
  http: ^1.2.2
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  intl_phone_field: ^3.2.0
  fl_chart: ^0.68.0
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0
  flutter_rating_bar: ^4.0.1
  retry: ^3.1.2
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  flutter_secure_storage: ^9.2.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/offers/
    - assets/services/
    - assets/saloons/
    - assets/favourites/
    - assets/images/default_logo.jpg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
